In [4]:
import numpy as np


# 1 zeros method... you can use the zeros method to create an array of all zeros as shown below:


In [12]:
zeros = np.zeros((5,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 2 zeros method.

In [20]:
zeros = np.zeros((4))
print(zeros)

[0. 0. 0. 0.]


# 3 zeros method.

In [22]:
zeros = np.zeros((5,1))
print(zeros)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]]


# 4 the array method.

In [16]:
x = [2, 3, 4, 5, 6]
nums = np.array([2, 3, 4, 5, 6])
type(nums)
print (x)
print (nums)

[2, 3, 4, 5, 6]
[2 3 4 5 6]


# 5 The numpy.repeat(a, repeats, axis=None) function repeats the elements of an array. The number of repetitions is specified by the second argument repeats.

In [23]:
np.repeat(3,5)

array([3, 3, 3, 3, 3])

In [28]:
v1='Sohail'
np.repeat(v1,5)

array(['Sohail', 'Sohail', 'Sohail', 'Sohail', 'Sohail'], dtype='<U6')

# 5 Ones Method

In [41]:
np.ones(5)

array([1., 1., 1., 1., 1.])

# 6 Ones Method

In [48]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 7 This method takes three arguments: a start index, end index, and the number of linearly-spaced numbers that you want between the specified range

In [58]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# 8 The eye method can be used to create an identity matrix

In [59]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [6]:
#9
null=np.zeros(10,"int64")
null

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [7]:
#10
V1=np.array(range(10,49))
V1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [10]:
#11
V1.shape 

(39,)

In [11]:
#12
V1.dtype

dtype('int32')

In [12]:
#13
type(V1)

numpy.ndarray

In [13]:
#14
np.__version__

'1.18.1'

In [14]:
#15
np.__config__


<module 'numpy.__config__' from 'C:\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>

In [15]:
#16
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Anaconda3\\Library\\include']
la

In [17]:
#17
arr1=np.array(range(10,30),dtype=bool)
arr1

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [23]:
#18
arr2=np.arange(16).reshape(8,2)
arr2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [24]:
#19
arr2.ndim

2

In [25]:
#20
arr3=np.arange(40).reshape(2,10,2)
arr3 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

In [26]:
#20
arr3.ndim

3

In [29]:
#21
V1[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [30]:
#22
null=np.zeros(10,"int64")
null[5]=1
null

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [31]:
#23
np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [32]:
#24
arry1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arry2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arry3=arry1*arry2
arry3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [33]:
#25
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3=arr1=arr2
arr3


array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [34]:
#26
val=np.arange(10)
val[val%2==1]

array([1, 3, 5, 7, 9])

In [35]:
#27
val=np.arange(10)                     
val[val%2==1]=-1
val

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [37]:
#28
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
#29
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
#30
arr[5]=12
arr[6]=12
arr[7]=12
arr[8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [42]:
#31
array=np.arange(20).reshape(4,5)
array[0:4]=0
array

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [43]:
#32
array[:,0]=1
array[:,4]=1
array

array([[1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

In [44]:
#33
array[0,:]=1
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1]])

In [45]:
#34
array[3,:]=1
array

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [46]:
#35
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
#36
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [48]:
#37
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
#38
arr3d.ndim

3

In [50]:
#39
arr=array[:1]
arr

array([[1, 1, 1, 1, 1]])

In [51]:
#40
array[0:2,0:3]

array([[1, 1, 1],
       [1, 0, 0]])

In [52]:
#41
array=np.arange(100).reshape(10,10)
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [53]:
#42
array.max()

99

In [54]:
#43
array.min()

0

In [60]:
#44
nam = np.array(['Sam', 'Ali', 'John', 'Sim', 'Gerry', 'James', 'Sim']) 
data = np.random.randn(7, 4)
data[nam!="sim"]

array([[-0.15296507,  0.23557945,  0.14348287, -0.09678919],
       [ 0.80730361, -0.38688106, -0.12041311, -0.18964955],
       [ 0.67955351, -0.43386401,  0.3078152 ,  0.56860815],
       [ 1.42288946,  0.71118949, -1.69594778,  0.84801647],
       [-0.54807776,  0.30875372, -0.8786607 , -1.56583613],
       [-0.15557555,  1.48028603,  1.54073364, -0.78547707],
       [ 1.21925498,  2.55353457, -1.36920529, -0.08644873]])

In [61]:
#45
array.astype(np.float)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.],
       [50., 51., 52., 53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69.],
       [70., 71., 72., 73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89.],
       [90., 91., 92., 93., 94., 95., 96., 97., 98., 99.]])

In [62]:
#46
array=np.arange(16).reshape(2,2,4)
array.astype(np.float)
np.swapaxes(array,0,1) #1 AXIS

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [63]:
#47
array/18

array([[[0.        , 0.05555556, 0.11111111, 0.16666667],
        [0.22222222, 0.27777778, 0.33333333, 0.38888889]],

       [[0.44444444, 0.5       , 0.55555556, 0.61111111],
        [0.66666667, 0.72222222, 0.77777778, 0.83333333]]])

In [64]:
#48
a=np.random.uniform(0,12,12)
b=np.random.uniform(0,12,12)
max(a) , max(b)

(10.436571251164228, 9.526868741608162)

In [66]:
#49
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [67]:
#50
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])